// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9XPaLoyrGVGXph8IUPpzVMdBw5MsMCE',
    appId: '1:300810315501:web:9b97bdde1a821b33630ee4',
    messagingSenderId: '300810315501',
    projectId: 'the-hotel-app-b10be',
    authDomain: 'the-hotel-app-b10be.firebaseapp.com',
    storageBucket: 'the-hotel-app-b10be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuagtdz75UEum_Bwx_N_l3Ogh2eXnNxfI',
    appId: '1:300810315501:android:c02b221e9cb0fbfb630ee4',
    messagingSenderId: '300810315501',
    projectId: 'the-hotel-app-b10be',
    storageBucket: 'the-hotel-app-b10be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDil8zfs1vWmu190K40Mgkx_vTnQYm0t9w',
    appId: '1:300810315501:ios:7da6448eb6b3c197630ee4',
    messagingSenderId: '300810315501',
    projectId: 'the-hotel-app-b10be',
    storageBucket: 'the-hotel-app-b10be.appspot.com',
    iosBundleId: 'com.aunsh.theHotelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDil8zfs1vWmu190K40Mgkx_vTnQYm0t9w',
    appId: '1:300810315501:ios:7da6448eb6b3c197630ee4',
    messagingSenderId: '300810315501',
    projectId: 'the-hotel-app-b10be',
    storageBucket: 'the-hotel-app-b10be.appspot.com',
    iosBundleId: 'com.aunsh.theHotelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr9XPaLoyrGVGXph8IUPpzVMdBw5MsMCE',
    appId: '1:300810315501:web:21a0785c6035cf22630ee4',
    messagingSenderId: '300810315501',
    projectId: 'the-hotel-app-b10be',
    authDomain: 'the-hotel-app-b10be.firebaseapp.com',
    storageBucket: 'the-hotel-app-b10be.appspot.com',
  );
}
