class Currency {
  final String code;
  final String name;

  Currency({required this.code, required this.name});
}

final List<Currency> currencies = [
  Currency(code:'AED(د.إ.)', name:'United Arab Emirates Dirham'),
  Currency(code:'AFN(؋)', name:'Afghan Afghani'),
  Currency(code:'ALL(Lek)', name:'Albanian Lek'),
  Currency(code:'AMD(֏)', name:'Armenian Dram'),
  Currency(code:'ANG(ƒ)', name:'Netherlands Antillean Guilder'),
  Currency(code:'AOA(Kz)', name:'Angolan Kwanza'),
  Currency(code:'ARS(\$)', name:'Argentine Peso'),
  Currency(code:'AUD(\$)', name:'Australian Dollar'),
  Currency(code:'AWG(ƒ)', name:'Aruban Guilder'),
  Currency(code:'AZN(₼)', name:'Azerbaijani Manat'),
  Currency(code:'BAM(KM)', name:'Bosnia and Herzegovina Convertible Mark'),
  Currency(code:'BBD(\$)', name:'Barbadian Dollar'),
  Currency(code:'BDT(৳)', name:'Bangladeshi Taka'),
  Currency(code:'BGN(лв)', name:'Bulgarian Lev'),
  Currency(code:'BHD(فلس)', name:'Bahraini Dinar'),
  Currency(code:'BIF(FBu)', name:'Burundian Franc'),
  Currency(code:'BMD(\$)', name:'Bermudian Dollar'),
  Currency(code:'BND(\$)', name:'Brunei Dollar'),
  Currency(code:'BOB(\$b)', name:'Bolivian Boliviano'),
  Currency(code:'BRL(R\$)', name:'Brazilian Real'),
  Currency(code:'BSD(\$)', name:'Bahamian Dollar'),
  Currency(code:'BTN(Nu)', name:'Bhutanese Ngultrum'),
  Currency(code:'BWP(P)', name:'Botswana Pula'),
  Currency(code:'BYN(Br)', name:'Belarusian Ruble'),
  Currency(code:'BZD(BZ\$)', name:'Belize Dollar'),
  Currency(code:'CAD(\$)', name:'Canadian Dollar'),
  Currency(code:'CDF(FC)', name:'Congolese Franc'),
  Currency(code:'CHF(CHF)', name:'Swiss Franc'),
  Currency(code:'CLP(\$)', name:'Chilean Peso'),
  Currency(code:'CNY(¥)', name:'Chinese Yuan'),
  Currency(code:'COP(\$)', name:'Colombian Peso'),
  Currency(code:'CRC(₡)', name:'Costa Rican Colón'),
  Currency(code:'CUC(CUC\$)', name:'Cuban Convertible Peso'),
  Currency(code:'CUP(₱)', name:'Cuban Peso'),
  Currency(code:'CVE(\$)', name:'Cape Verdean Escudo'),
  Currency(code:'CZK(Kč)', name:'Czech Koruna'),
  Currency(code:'DJF(Fdj)', name:'Djiboutian Franc'),
  Currency(code:'DKK(kr)', name:'Danish Krone'),
  Currency(code:'DOP(RD\$)', name:'Dominican Peso'),
  Currency(code:'DZD(دج)', name:'Algerian Dinar'),
  Currency(code:'EGP(£)', name:'Egyptian Pound'),
  Currency(code:'ERN(Nfk)', name:'Eritrean Nakfa'),
  Currency(code:'ETB(ብር))', name:'Ethiopian Birr'),
  Currency(code:'EUR(€)', name:'Euro'),
  Currency(code:'FJD(\$)', name:'Fijian Dollar'),
  Currency(code:'FKP(£)', name:'Falkland Islands Pound'),
  Currency(code:'GBP(£)', name:'British Pound'),
  Currency(code:'GEL(₾)', name:'Georgian Lari'),
  Currency(code:'GGP(£)', name:'Guernsey Pound'),
  Currency(code:'GHS(¢)', name:'Ghanaian Cedi'),
  Currency(code:'GIP(£)', name:'Gibraltar Pound'),
  Currency(code:'GMD(GMD)', name:'Gambian Dalasi'),
  Currency(code:'GNF(GFr)', name:'Guinean Franc'),
  Currency(code:'GTQ(Q)', name:'Guatemalan Quetzal'),
  Currency(code:'GYD(\$)', name:'Guyanese Dollar'),
  Currency(code:'HKD(\$)', name:'Hong Kong Dollar'),
  Currency(code:'HNL(L)', name:'Honduran Lempira'),
  Currency(code:'HRK(kn)', name:'Croatian Kuna'),
  Currency(code:'HTG(HTG)', name:'Haitian Gourde'),
  Currency(code:'HUF(Ft)', name:'Hungarian Forint'),
  Currency(code:'IDR(Rp)', name:'Indonesian Rupiah'),
  Currency(code:'ILS(₪)', name:'Israeli New Shekel'),
  Currency(code:'IMP(£)', name:'Manx Pound'),
  Currency(code:'INR(₹)', name:'Indian Rupee'),
  Currency(code:'IQD(ع.د)', name:'Iraqi Dinar'),
  Currency(code:'IRR(﷼)', name:'Iranian Rial'),
  Currency(code:'ISK(kr)', name:'Icelandic Króna'),
  Currency(code:'JEP(£)', name:'Jersey Pound'),
  Currency(code:'JMD(J\$)', name:'Jamaican Dollar'),
  Currency(code:'JOD(JD)', name:'Jordanian Dinar'),
  Currency(code:'JPY(¥)', name:'Japanese Yen'),
  Currency(code:'KES(KES)', name:'Kenyan Shilling'),
  Currency(code:'KGS(лв)', name:'Kyrgyzstani Som'),
  Currency(code:'KHR(៛)', name:'Cambodian Riel'),
  Currency(code:'KID(\$)', name:'Kiribati Dollar'),
  Currency(code:'KMF(KMF)', name:'Comorian Franc'),
  Currency(code:'KPW(₩)', name:'North Korean Won'),
  Currency(code:'KRW(₩)', name:'South Korean Won'),
  Currency(code:'KWD(د.ك)', name:'Kuwaiti Dinar'),
  Currency(code:'KYD(\$)', name:'Cayman Islands Dollar'),
  Currency(code:'KZT(лв)', name:'Kazakhstani Tenge'),
  Currency(code:'LAK(₭)', name:'Lao Kip'),
  Currency(code:'LBP(£)', name:'Lebanese Pound'),
  Currency(code:'LKR(Rs)', name:'Sri Lankan Rupee'),
  Currency(code:'LRD(\$)', name:'Liberian Dollar'),
  Currency(code:'LSL(LSL)', name:'Lesotho Loti'),
  Currency(code:'LYD(ل.د)', name:'Libyan Dinar'),
  Currency(code:'MAD(د.م.)', name:'Moroccan Dirham'),
  Currency(code:'MDL(MDL)', name:'Moldovan Leu'),
  Currency(code:'MGA(Ar)', name:'Malagasy Ariary'),
  Currency(code:'MKD(ден)', name:'Macedonian Denar'),
  Currency(code:'MMK(MMK)', name:'Burmese Kyat'),
  Currency(code:'MNT(₮)', name:'Mongolian Tögrög'),
  Currency(code:'MOP(MOP\$)', name:'Macanese Pataca'),
  Currency(code:'MRU(MRU)', name:'Mauritanian Ouguiya'),
  Currency(code:'MUR(Rs)', name:'Mauritian Rupee'),
  Currency(code:'MVR(ރ)', name:'Maldivian Rufiyaa'),
  Currency(code:'MWK(MWK)', name:'Malawian Kwacha'),
  Currency(code:'MXN(\$)', name:'Mexican Peso'),
  Currency(code:'MYR(RM)', name:'Malaysian Ringgit'),
  Currency(code:'MZN(MT)', name:'Mozambican Metical'),
  Currency(code:'NAD(\$)', name:'Namibian Dollar'),
  Currency(code:'NGN(₦)', name:'Nigerian Naira'),
  Currency(code:'NIO(C\$)', name:'Nicaraguan Córdoba'),
  Currency(code:'NOK(kr)', name:'Norwegian Krone'),
  Currency(code:'NPR(Rs)', name:'Nepalese Rupee'),
  Currency(code:'NZD(\$)', name:'New Zealand Dollar'),
  Currency(code:'OMR(﷼)', name:'Omani Rial'),
  Currency(code:'PAB(B/.)', name:'Panamanian Balboa'),
  Currency(code:'PEN(S/.)', name:'Peruvian Sol'),
  Currency(code:'PGK(PGK)', name:'Papua New Guinean Kina'),
  Currency(code:'PHP(₱)', name:'Philippine Peso'),
  Currency(code:'PKR(Rs)', name:'Pakistani Rupee'),
  Currency(code:'PLN(zł)', name:'Polish Złoty'),
  Currency(code:'PYG(Gs)', name:'Paraguayan Guaraní'),
  Currency(code:'QAR(﷼)', name:'Qatari Riyal'),
  Currency(code:'RON(lei)', name:'Romanian Leu'),
  Currency(code:'RSD(Дин.)', name:'Serbian Dinar'),
  Currency(code:'RUB(₽)', name:'Russian Ruble'),
  Currency(code:'RWF(RWF)', name:'Rwandan Franc'),
  Currency(code:'SAR(﷼)', name:'Saudi Riyal'),
  Currency(code:'SBD(\$)', name:'Seychelles Rupees'),
  Currency(code:'SCR(Rs)', name:'Seychelles Rupees'),
  Currency(code:'SEK(kr)', name:'Swedish Krona'),
  Currency(code:'SGD(\$)', name:'Singapore Dollar'),
  Currency(code:'SHP(£)', name:'Saint Helena Pound'),
  Currency(code:'SLL(SLL)', name:'Sierra Leonean Leone'),
  Currency(code:'SOS(SOS)', name:'Somali Shilling'),
  Currency(code:'SRD(\$)', name:'Surinamese Dollar'),
  Currency(code:'SSP(£)', name:'South Sudanese Pound'),
  Currency(code:'STN(STD)', name:'São Tomé and Príncipe Dobra'),
  Currency(code:'SVC(\$)', name:'El Salvador Colon'),
  Currency(code:'SYP(£)', name:'Syrian Pound'),
  Currency(code:'SZL(SZL)', name:'Swazi Lilangeni'),
  Currency(code:'THB(฿)', name:'Thai Baht'),
  Currency(code:'TJS(SM)', name:'Tajikistani Somoni'),
  Currency(code:'TMT(TMT)', name:'Turkmenistan Manat'),
  Currency(code:'TND(د.ت)', name:'Tunisian Dinar'),
  Currency(code:'TOP(T\$)', name:'Tongan Paʻanga'),
  Currency(code:'TRY(₺)', name:'Turkish Lira'),
  Currency(code:'TTD(TT\$)', name:'Trinidad and Tobago Dollar'),
  Currency(code:'TVD(\$)', name:'Tuvaluan Dollar'),
  Currency(code:'TWD(\$)', name:'New Taiwan Dollar'),
  Currency(code:'TZS(TZS)', name:'Tanzanian Shilling'),
  Currency(code:'UAH(₴)', name:'Ukrainian Hryvnia'),
  Currency(code:'UGX(UGX)', name:'Ugandan Shilling'),
  Currency(code:'USD(\$)', name:'United States Dollar'),
  Currency(code:'UYU(\$U)', name:'Uruguayan Peso'),
  Currency(code:'UZS(лв)', name:'Uzbekistani Soʻm'),
  Currency(code:'VEF(Bs)', name:'Venezuelan Bolívar'),
  Currency(code:'VND(₫)', name:'Vietnamese Dồng'),
  Currency(code:'VUV(VUV)', name:'Vanuatu Vatu'),
  Currency(code:'WST(SAT)', name:'Samoan Tālā'),
  Currency(code:'XAF(FCFA)', name:'Central African CFA Franc'),
  Currency(code:'XCD(EC\$)', name:'Eastern Caribbean Dollar'),
  Currency(code:'XOF(CFA)', name:'West African CFA Franc'),
  Currency(code:'XPF(CFPF)', name:'CFP Franc'),
  Currency(code:'YER(﷼)', name:'YEMEN RIAL'),
  Currency(code:'ZAR(R)', name:'South African Rand'),
  Currency(code:'ZMW(ZMW)', name:'Zambian Kwacha'),
  Currency(code:'ZWB(Z\$)', name:'Zimbabwean Dollar'),
];