class PhoneFormat {
  final String country;
  final String code;

  PhoneFormat({required this.country, required this.code});
}

final List<PhoneFormat> phoneFormats = [
  PhoneFormat(country: 'Afghanistan', code: '+93'),
  PhoneFormat(country: 'Albania', code: '+355'),
  PhoneFormat(country: 'Algeria', code: '+213'),
  PhoneFormat(country: 'Andorra', code: '+376'),
  PhoneFormat(country: 'Angola', code: '+244'),
  PhoneFormat(country: 'Antigua and Barbuda', code: '+1-268'),
  PhoneFormat(country: 'Argentina', code: '+54'),
  PhoneFormat(country: 'Armenia', code: '+374'),
  PhoneFormat(country: 'Australia', code: '+61'),
  PhoneFormat(country: 'Austria', code: '+43'),
  PhoneFormat(country: 'Azerbaijan', code: '+994'),
  PhoneFormat(country: 'Bahamas', code: '+1-242'),
  PhoneFormat(country: 'Bahrain', code: '+973'),
  PhoneFormat(country: 'Bangladesh', code: '+880'),
  PhoneFormat(country: 'Barbados', code: '+1-246'),
  PhoneFormat(country: 'Belarus', code: '+375'),
  PhoneFormat(country: 'Belgium', code: '+32'),
  PhoneFormat(country: 'Belize', code: '+501'),
  PhoneFormat(country: 'Benin', code: '+229'),
  PhoneFormat(country: 'Bhutan', code: '+975'),
  PhoneFormat(country: 'Bolivia', code: '+591'),
  PhoneFormat(country: 'Bosnia and Herzegovina', code: '+387'),
  PhoneFormat(country: 'Botswana', code: '+267'),
  PhoneFormat(country: 'Brazil', code: '+55'),
  PhoneFormat(country: 'Brunei', code: '+673'),
  PhoneFormat(country: 'Bulgaria', code: '+359'),
  PhoneFormat(country: 'Burkina Faso', code: '+226'),
  PhoneFormat(country: 'Burundi', code: '+257'),
  PhoneFormat(country: 'Cabo Verde', code: '+238'),
  PhoneFormat(country: 'Cambodia', code: '+855'),
  PhoneFormat(country: 'Cameroon', code: '+237'),
  PhoneFormat(country: 'Canada', code: '+1'),
  PhoneFormat(country: 'Central African Republic', code: '+236'),
  PhoneFormat(country: 'Chad', code: '+235'),
  PhoneFormat(country: 'Chile', code: '+56'),
  PhoneFormat(country: 'China', code: '+86'),
  PhoneFormat(country: 'Colombia', code: '+57'),
  PhoneFormat(country: 'Comoros', code: '+269'),
  PhoneFormat(country: 'Congo (Congo-Brazzaville)', code: '+242'),
  PhoneFormat(country: 'Costa Rica', code: '+506'),
  PhoneFormat(country: 'Croatia', code: '+385'),
  PhoneFormat(country: 'Cuba', code: '+53'),
  PhoneFormat(country: 'Cyprus', code: '+357'),
  PhoneFormat(country: 'Czech Republic', code: '+420'),
  PhoneFormat(country: 'Democratic Republic of the Congo', code: '+243'),
  PhoneFormat(country: 'Denmark', code: '+45'),
  PhoneFormat(country: 'Djibouti', code: '+253'),
  PhoneFormat(country: 'Dominica', code: '+1-767'),
  PhoneFormat(country: 'Dominican Republic', code: '+1-809'),
  PhoneFormat(country: 'Ecuador', code: '+593'),
  PhoneFormat(country: 'Egypt', code: '+20'),
  PhoneFormat(country: 'El Salvador', code: '+503'),
  PhoneFormat(country: 'Equatorial Guinea', code: '+240'),
  PhoneFormat(country: 'Eritrea', code: '+291'),
  PhoneFormat(country: 'Estonia', code: '+372'),
  PhoneFormat(country: 'Eswatini', code: '+268'),
  PhoneFormat(country: 'Ethiopia', code: '+251'),
  PhoneFormat(country: 'Fiji', code: '+679'),
  PhoneFormat(country: 'Finland', code: '+358'),
  PhoneFormat(country: 'France', code: '+33'),
  PhoneFormat(country: 'Gabon', code: '+241'),
  PhoneFormat(country: 'Gambia', code: '+220'),
  PhoneFormat(country: 'Georgia', code: '+995'),
  PhoneFormat(country: 'Germany', code: '+49'),
  PhoneFormat(country: 'Ghana', code: '+233'),
  PhoneFormat(country: 'Greece', code: '+30'),
  PhoneFormat(country: 'Grenada', code: '+1-473'),
  PhoneFormat(country: 'Guatemala', code: '+502'),
  PhoneFormat(country: 'Guinea', code: '+224'),
  PhoneFormat(country: 'Guinea-Bissau', code: '+245'),
  PhoneFormat(country: 'Guyana', code: '+592'),
  PhoneFormat(country: 'Haiti', code: '+509'),
  PhoneFormat(country: 'Honduras', code: '+504'),
  PhoneFormat(country: 'Hungary', code: '+36'),
  PhoneFormat(country: 'Iceland', code: '+354'),
  PhoneFormat(country: 'India', code: '+91'),
  PhoneFormat(country: 'Indonesia', code: '+62'),
  PhoneFormat(country: 'Iran', code: '+98'),
  PhoneFormat(country: 'Iraq', code: '+964'),
  PhoneFormat(country: 'Ireland', code: '+353'),
  PhoneFormat(country: 'Israel', code: '+972'),
  PhoneFormat(country: 'Italy', code: '+39'),
  PhoneFormat(country: 'Jamaica', code: '+1-876'),
  PhoneFormat(country: 'Japan', code: '+81'),
  PhoneFormat(country: 'Jordan', code: '+962'),
  PhoneFormat(country: 'Kazakhstan', code: '+7'),
  PhoneFormat(country: 'Kenya', code: '+254'),
  PhoneFormat(country: 'Kiribati', code: '+686'),
  PhoneFormat(country: 'Kuwait', code: '+965'),
  PhoneFormat(country: 'Kyrgyzstan', code: '+996'),
  PhoneFormat(country: 'Laos', code: '+856'),
  PhoneFormat(country: 'Latvia', code: '+371'),
  PhoneFormat(country: 'Lebanon', code: '+961'),
  PhoneFormat(country: 'Lesotho', code: '+266'),
  PhoneFormat(country: 'Liberia', code: '+231'),
  PhoneFormat(country: 'Libya', code: '+218'),
  PhoneFormat(country: 'Liechtenstein', code: '+423'),
  PhoneFormat(country: 'Lithuania', code: '+370'),
  PhoneFormat(country: 'Luxembourg', code: '+352'),
  PhoneFormat(country: 'Madagascar', code: '+261'),
  PhoneFormat(country: 'Malawi', code: '+265'),
  PhoneFormat(country: 'Malaysia', code: '+60'),
  PhoneFormat(country: 'Maldives', code: '+960'),
  PhoneFormat(country: 'Mali', code: '+223'),
  PhoneFormat(country: 'Malta', code: '+356'),
  PhoneFormat(country: 'Marshall Islands', code: '+692'),
  PhoneFormat(country: 'Mauritania', code: '+222'),
  PhoneFormat(country: 'Mauritius', code: '+230'),
  PhoneFormat(country: 'Mexico', code: '+52'),
  PhoneFormat(country: 'Micronesia', code: '+691'),
  PhoneFormat(country: 'Moldova', code: '+373'),
  PhoneFormat(country: 'Monaco', code: '+377'),
  PhoneFormat(country: 'Mongolia', code: '+976'),
  PhoneFormat(country: 'Montenegro', code: '+382'),
  PhoneFormat(country: 'Morocco', code: '+212'),
  PhoneFormat(country: 'Mozambique', code: '+258'),
  PhoneFormat(country: 'Myanmar', code: '+95'),
  PhoneFormat(country: 'Namibia', code: '+264'),
  PhoneFormat(country: 'Nauru', code: '+674'),
  PhoneFormat(country: 'Nepal', code: '+977'),
  PhoneFormat(country: 'Netherlands', code: '+31'),
  PhoneFormat(country: 'New Zealand', code: '+64'),
  PhoneFormat(country: 'Nicaragua', code: '+505'),
  PhoneFormat(country: 'Niger', code: '+227'),
  PhoneFormat(country: 'Nigeria', code: '+234'),
  PhoneFormat(country: 'North Macedonia', code: '+389'),
  PhoneFormat(country: 'Norway', code: '+47'),
  PhoneFormat(country: 'Oman', code: '+968'),
  PhoneFormat(country: 'Pakistan', code: '+92'),
  PhoneFormat(country: 'Palau', code: '+680'),
  PhoneFormat(country: 'Panama', code: '+507'),
  PhoneFormat(country: 'Papua New Guinea', code: '+675'),
  PhoneFormat(country: 'Paraguay', code: '+595'),
  PhoneFormat(country: 'Peru', code: '+51'),
  PhoneFormat(country: 'Philippines', code: '+63'),
  PhoneFormat(country: 'Poland', code: '+48'),
  PhoneFormat(country: 'Portugal', code: '+351'),
  PhoneFormat(country: 'Qatar', code: '+974'),
  PhoneFormat(country: 'Romania', code: '+40'),
  PhoneFormat(country: 'Russia', code: '+7'),
  PhoneFormat(country: 'Rwanda', code: '+250'),
  PhoneFormat(country: 'Saint Kitts and Nevis', code: '+1-869'),
  PhoneFormat(country: 'Saint Lucia', code: '+1-758'),
  PhoneFormat(country: 'Saint Vincent and the Grenadines', code: '+1-784'),
  PhoneFormat(country: 'Samoa', code: '+685'),
  PhoneFormat(country: 'San Marino', code: '+378'),
  PhoneFormat(country: 'Sao Tome and Principe', code: '+239'),
  PhoneFormat(country: 'Saudi Arabia', code: '+966'),
  PhoneFormat(country: 'Senegal', code: '+221'),
  PhoneFormat(country: 'Serbia', code: '+381'),
  PhoneFormat(country: 'Seychelles', code: '+248'),
  PhoneFormat(country: 'Sierra Leone', code: '+232'),
  PhoneFormat(country: 'Singapore', code: '+65'),
  PhoneFormat(country: 'Slovakia', code: '+421'),
  PhoneFormat(country: 'Slovenia', code: '+386'),
  PhoneFormat(country: 'Solomon Islands', code: '+677'),
  PhoneFormat(country: 'Somalia', code: '+252'),
  PhoneFormat(country: 'South Africa', code: '+27'),
  PhoneFormat(country: 'South Korea', code: '+82'),
  PhoneFormat(country: 'South Sudan', code: '+211'),
  PhoneFormat(country: 'Spain', code: '+34'),
  PhoneFormat(country: 'Sri Lanka', code: '+94'),
  PhoneFormat(country: 'Sudan', code: '+249'),
  PhoneFormat(country: 'Suriname', code: '+597'),
  PhoneFormat(country: 'Sweden', code: '+46'),
  PhoneFormat(country: 'Switzerland', code: '+41'),
  PhoneFormat(country: 'Syria', code: '+963'),
  PhoneFormat(country: 'Taiwan', code: '+886'),
  PhoneFormat(country: 'Tajikistan', code: '+992'),
  PhoneFormat(country: 'Tanzania', code: '+255'),
  PhoneFormat(country: 'Thailand', code: '+66'),
  PhoneFormat(country: 'Timor-Leste', code: '+670'),
  PhoneFormat(country: 'Togo', code: '+228'),
  PhoneFormat(country: 'Tonga', code: '+676'),
  PhoneFormat(country: 'Trinidad and Tobago', code: '+1-868'),
  PhoneFormat(country: 'Tunisia', code: '+216'),
  PhoneFormat(country: 'Turkey', code: '+90'),
  PhoneFormat(country: 'Turkmenistan', code: '+993'),
  PhoneFormat(country: 'Tuvalu', code: '+688'),
  PhoneFormat(country: 'Uganda', code: '+256'),
  PhoneFormat(country: 'Ukraine', code: '+380'),
  PhoneFormat(country: 'United Arab Emirates', code: '+971'),
  PhoneFormat(country: 'United Kingdom', code: '+44'),
  PhoneFormat(country: 'United States', code: '+1'),
  PhoneFormat(country: 'Uruguay', code: '+598'),
  PhoneFormat(country: 'Uzbekistan', code: '+998'),
  PhoneFormat(country: 'Vanuatu', code: '+678'),
  PhoneFormat(country: 'Vatican City', code: '+39'),
  PhoneFormat(country: 'Venezuela', code: '+58'),
  PhoneFormat(country: 'Vietnam', code: '+84'),
  PhoneFormat(country: 'Yemen', code: '+967'),
  PhoneFormat(country: 'Zambia', code: '+260'),
  PhoneFormat(country: 'Zimbabwe', code: '+263'),
];